### ISSUE TITLE
How to run SMAC env with the presented code

### ISSUE THREAD

**Issue by HyunghoNa** [semitable/seps#2]
Hello.
Firstly, thanks for sharing your nice research and code.

I have been working on MARL as you and especially on SMAC environment.

I run your code in window os so as to understand line by line, but have some issue on working with SMAC env.

I have some questions on your remark,

"Similarly, LBF and SMAC can be run as long as they are registered in gym."

and
 
 (Careful! Requires installation of SC2 which is a large package. For our implementation you must remove that SMACCompatible wrapper from the configuration, by removing the respective line in ac.py:config)

1. how to register SMAC env to gym so that the code gets the required information of the environment as it does from gym.
  
Since i couldn't figure out 1. I tried to SMAC-env as it is, but it drove me to next question.

2.  there was about a mention on wrapper, but I got confused. Do we need to "remove" the wrapper or "use" the wrapper? since the environment information of SMAC is different from that of gym, it seems to modify some information to generate the required information such as "actions_mask" which is not directly utilizable in SMAC. Above all in order to work with your code, variables need to be in a right shape and this also requires some variable modification.

Thus, I was working on revising your code to run SMAC without running "_make_envs()", but it requires more and more debugging. Hence, I was wondering if there is an easier way to do this.

Thank you for reading this long question.

**Comment by semitable** [comment]
Hi,

To run SMAC you need to register it as a gym environment. A quick example is to use the wrapper below:
```python
from smac.env import StarCraft2Env
import numpy as np
from gym.spaces import Box, Discrete, Tuple, Dict
from gym.core import Env


class GymmaStarCraftWrapper(Env):
    def __init__(self, map_name):

        self._env = StarCraft2Env(map_name=map_name, reward_sparse=False)

        env_info = self._env.get_env_info()
        n_agents = env_info["n_agents"]
        n_actions = env_info["n_actions"]
        sa_obs = Box(
            low=-float("inf"),
            high=float("inf"),
            shape=(self._env.get_obs_size(),),
            dtype=np.float32,
        )

        self.action_space = Tuple(tuple([Discrete(n_actions) for _ in range(n_agents)]))
        self.observation_space = Tuple(tuple([sa_obs for _ in range(n_agents)]))
        self.n_agents = n_agents

        self.state_size = env_info["state_shape"]

    def reset(self):
        self._env.reset()
        return tuple(self._env.get_obs())

    def render(self):
        pass

    def get_state(self):
        return self._env.get_state()

    def get_avail_actions(self):
        return self._env.get_avail_actions()

    def step(self, actions):
        # print(actions)
        avail = self._env.get_avail_actions()
        factions = []
        for agent, action in enumerate(actions):
            if avail[agent][action] > 0:
                factions.append(action)
                continue
            avail_actions = avail[agent]
            avail_actions_ind = np.nonzero(avail_actions)[0]
            action = np.random.choice(avail_actions_ind)
            factions.append(action)

        reward, done, info = self._env.step(factions)
        rewards = self.n_agents * [reward]
        dones = self.n_agents * [done]
        # obs = tuple(self._env.get_obs())
        obs = self._env.get_obs()
        avail_actions = self._env.get_avail_actions()
        info["avail_actions"] = avail_actions
        return tuple(obs), rewards, dones, info

    def close(self):
        self._env.close()
```

To actually register stuff you need to use something like:
```python
    for e in (
        "3m",
        "8m",
        "5m_vs_6m",
        "6h_vs_8z",
        "3s_vs_3z",
        "3s_vs_4z",
        "3s_vs_5z",
        "MMM2",
        "2s3z",
        "3s5z",
    ):
        gymkey = f"smac-{e}-v0"
        register(
            gymkey,
            entry_point="MODULENAME:GymmaStarCraftWrapper",
            kwargs={"map_name": e,},
        )
        registry.spec(gymkey).gymma_wrappers = tuple()
```
be sure to change MODULENAME to the path that points to the wrapper provided above.

For (2), you need to REMOVE the wrapper in ac.py line 55 (i.e. comment out `SMACCompatible,`. It is used so that other environments have a similar API, but if you use it in SMAC it will overwrite stuff.

Thanks!

**Comment by HyunghoNa** [comment]
Thank you for your rapid and kind reply. After applying your comments to the code, it works as expected. Thanks again!
